Kill invalid dep file.
GTNewHorizons/ForgeMultipart pull request #6
Opened 2021-12-10 06:04 UTC by mitchej123

It's invalid as is (not currently having the vars replaced), and CCL is shipped with the modpack.

2021-12-10 08:26 UTC, SinTh0r4s commented
Simply removing the file might not be sufficient, since it is referenced in https://github.com/GTNewHorizons/ForgeMultipart/blob/aef46a88519bc36b2941a0ce490bcc3947409325/src/main/scala/codechicken/core/launch/DepLoader.java#L504. It might be, that you can fully remove the DepLoader as file and core mod, but I have not checked any cross mod dependencies yet.

2021-12-14 19:27 UTC, bombcar approved these changes
You can remove it, the check looks for it and doesn't care if it is missing.

2021-12-15 07:56 UTC, SinTh0r4s requested changes
You may do so, but it is likely you would leave dead code in the repository.

2021-12-15 12:33 UTC, bombcar commented
> You may do so, but it is likely you would leave dead code in the repository.

Attempts (by me) to remove that dead code stopped mods from loading (codechickencore)

2021-12-15 13:03 UTC, SinTh0r4s commented
> Attempts (by me) to remove that dead code stopped mods from loading (codechickencore)

Super weird! CCC provides it's own DepLoader

2021-12-15 13:07 UTC, bombcar commented
Ahahahaaha there was a typo - fixing

2021-12-15 13:09 UTC, bombcar commented
Let's handle this in https://github.com/GTNewHorizons/ForgeMultipart/pull/7

2021-12-15 13:09 UTC, closed without merging